### ISSUE TITLE
"." is not recognized when start

### ISSUE THREAD

**Issue by maenemos** [JohnLindahlTech/pass-bokning#3]
when I run pnpm run start
I get this error 
./src/entry.mjs
'.' is not recognized as an internal or external command,
operable program or batch file.

**Comment by JohnLindahlTech** [comment]
Try now with latest code. Also which OS do you run? (Windows, linux, macos)

**Comment by maenemos** [comment]
I run it on windows VSC
I made sure that I have correct node version
pulled the last commit and still same issue but with: sh is not recognized
________________________________

**Comment by JohnLindahlTech** [comment]
Ah ok. I have not actually run it on Windows (I run wsl) Will look into it later.

**Comment by maenemos** [comment]
Maybe this pnpm-debug-log  can help 
{
  "0 debug pnpm:scope": {
    "selected": 1
  },
  "1 error pnpm": {
    "errno": 1,
    "code": "ELIFECYCLE",
    "pkgid": "passbokning@1.0.0",
    "stage": "start",
    "script": "sh ./src/entry.mjs",
    "pkgname": "passbokning",
    "err": {
      "name": "Error",
      "message": "passbokning@1.0.0 start: `sh ./src/entry.mjs`\nExit status 1",
      "code": "ELIFECYCLE",
      "stack": "Error: passbokning@1.0.0 start: `sh ./src/entry.mjs`\nExit status 1\n    at EventEmitter.<anonymous> (C:\\Users\\mypcpriv\\.node\\corepack\\pnpm\\6.11.0\\dist\\pnpm.cjs:104774:20)\n    at EventEmitter.emit (node:events:390:28)\n    at ChildProcess.<anonymous> (C:\\Users\\mypcpriv\\.node\\corepack\\pnpm\\6.11.0\\dist\\pnpm.cjs:93080:18)\n    at ChildProcess.emit (node:events:390:28)\n    at maybeClose (node:internal/child_process:1064:16)\n    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)"
    }
  }
}

**Comment by JohnLindahlTech** [comment]
I have updated now so `pnpm run start` actually runs `node ./src/entry.mjs` this should make things work for you as long as you have the `node` runtime properly installed. Please reopen if that is not the case. (I have only debugged the runtime, and not made sure everything works with the entire script, but I forsee no issued there)

**Comment by maenemos** [comment]
Works fine now 
thank you 
Hatten av
